### ISSUE TITLE
Some public var-s of TableViewIndex not visible from Objective-C

### ISSUE THREAD

**Issue by dgarkusha** [mindz-eye/MYTableViewIndex#13]
Hi,

Thanks for the nice library!

I would like to report one small issue that I found while integrating the lib into an Objective-C project.
The problem is that _indexInset_, _indexOffset_ and _itemSpacing_ var-s are missing in auto-generated header and can not be accessed from Objective C. At the same time, when you edit library code and try to specify a different name for any of those properties via @objc(...), compiler starts showing "Property cannot be marked @objc because its type cannot be represented in Objective-C" error.

I made a small investigation and found that _indexInset_ and _indexOffset_ were visible correctly until 510e329ac18bba7c4900150aa2988f94ff1e3721. So, the problem appeared as soon as those struct-s became implicitly unwrapped optionals.
If I now simply change them back in a way that they wouldn't be optionals anymore, the problem disappears. If on your opinion this is ok (maybe there is a better solution...), I'll do a merge request.

**Comment by backofthecup** [comment]
Very nice control. Any chance the Objective C issues will be worked out soon?

**Comment by mindz-eye** [comment]
I tried to express a null_resettable behavior, but as it turned out, Xcode header generator yields _Null_unspecified for implicitly unwrapped optionals instead. And it obviously can not import optional structs :(
To achieve the desired behavior we need to make them non-optionals and add an explicit resetFont/Inset/Offset/Spacing methods. A bit ugly solution though.

>  If on your opinion this is ok (maybe there is a better solution...), I'll do a merge request.

Yeah, I think reverting to non-optionals is ok for now.
